<?php
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4586'	WHERE EMP_N = 2563 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4583'	WHERE EMP_N = 2567 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4582'	WHERE EMP_N = 2569 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4645'	WHERE EMP_N = 2570 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4585'	WHERE EMP_N = 2571 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4689'	WHERE EMP_N = 2574 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4609'	WHERE EMP_N = 2578 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4530'	WHERE EMP_N = 2579 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4627'	WHERE EMP_N = 2580 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4615'	WHERE EMP_N = 2581 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4290'	WHERE EMP_N = 2582 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4422'	WHERE EMP_N = 2585 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3684'	WHERE EMP_N = 2593 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4009'	WHERE EMP_N = 2594 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4503'	WHERE EMP_N = 2595 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4475'	WHERE EMP_N = 2598 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4005'	WHERE EMP_N = 2602 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4703'	WHERE EMP_N = 2608 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4704'	WHERE EMP_N = 2610 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4702'	WHERE EMP_N = 2612 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4672'	WHERE EMP_N = 2614 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4676'	WHERE EMP_N = 2615 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4665'	WHERE EMP_N = 2616 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4722'	WHERE EMP_N = 2619 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4666'	WHERE EMP_N = 2620 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4448'	WHERE EMP_N = 2621 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4557'	WHERE EMP_N = 2622 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4697'	WHERE EMP_N = 2623 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4669'	WHERE EMP_N = 2624 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4742'	WHERE EMP_N = 2625 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4677'	WHERE EMP_N = 2626 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4605'	WHERE EMP_N = 2628 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4752'	WHERE EMP_N = 2654 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4745'	WHERE EMP_N = 2655 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4743'	WHERE EMP_N = 2656 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4744'	WHERE EMP_N = 2657 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4756'	WHERE EMP_N = 2658 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4757'	WHERE EMP_N = 2659 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4772'	WHERE EMP_N = 2663 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4740'	WHERE EMP_N = 2664 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4755'	WHERE EMP_N = 2667 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4753'	WHERE EMP_N = 2668 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4758'	WHERE EMP_N = 2669 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4495'	WHERE EMP_N = 2670 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4739'	WHERE EMP_N = 2671 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4737'	WHERE EMP_N = 2673 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4725'	WHERE EMP_N = 2674 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4813'	WHERE EMP_N = 2680 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4759'	WHERE EMP_N = 2681 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4685'	WHERE EMP_N = 2684 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3090'	WHERE EMP_N = 2689 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4812'	WHERE EMP_N = 2695 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4811'	WHERE EMP_N = 2697 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4814'	WHERE EMP_N = 2702 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4820'	WHERE EMP_N = 2703 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4845'	WHERE EMP_N = 2704 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4937'	WHERE EMP_N = 2710 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4819'	WHERE EMP_N = 2711 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4654'	WHERE EMP_N = 2712 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4749'	WHERE EMP_N = 2714 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4818'	WHERE EMP_N = 2719 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3806'	WHERE EMP_N = 2720 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4678'	WHERE EMP_N = 2722 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4766'	WHERE EMP_N = 2726 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4735'	WHERE EMP_N = 2727 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4769'	WHERE EMP_N = 2728 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4730'	WHERE EMP_N = 2729 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4683'	WHERE EMP_N = 2730 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4837'	WHERE EMP_N = 2731 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3789'	WHERE EMP_N = 2732 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4770'	WHERE EMP_N = 2733 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4771'	WHERE EMP_N = 2735 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4529'	WHERE EMP_N = 2737 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4724'	WHERE EMP_N = 2741 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4721'	WHERE EMP_N = 2743 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4681'	WHERE EMP_N = 2744 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '1891'	WHERE EMP_N = 2746 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4732'	WHERE EMP_N = 2747 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4688'	WHERE EMP_N = 2748 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4846'	WHERE EMP_N = 2750 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4858'	WHERE EMP_N = 2752 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4671'	WHERE EMP_N = 2753 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4680'	WHERE EMP_N = 2754 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4698'	WHERE EMP_N = 2755 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4767'	WHERE EMP_N = 2756 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4781'	WHERE EMP_N = 2758 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4692'	WHERE EMP_N = 2759 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4750'	WHERE EMP_N = 2761 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4777'	WHERE EMP_N = 2762 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4454'	WHERE EMP_N = 2763 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4695'	WHERE EMP_N = 2764 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4694'	WHERE EMP_N = 2771 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3822'	WHERE EMP_N = 2774 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '1234'	WHERE EMP_N = 2778 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4787'	WHERE EMP_N = 2779 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3817'	WHERE EMP_N = 2781 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4573'	WHERE EMP_N = 2782 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4607'	WHERE EMP_N = 2783 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4532'	WHERE EMP_N = 2784 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4686'	WHERE EMP_N = 2785 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3812'	WHERE EMP_N = 2786 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4690'	WHERE EMP_N = 2788 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4640'	WHERE EMP_N = 2789 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4856'	WHERE EMP_N = 2791 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4839'	WHERE EMP_N = 2792 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4733'	WHERE EMP_N = 2793 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4675'	WHERE EMP_N = 2794 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3636'	WHERE EMP_N = 2795 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4729'	WHERE EMP_N = 2797 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '9003'	WHERE EMP_N = 2802 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4421'	WHERE EMP_N = 2806 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4866'	WHERE EMP_N = 2812 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4650'	WHERE EMP_N = 2818 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5456'	WHERE EMP_N = 2820 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4674'	WHERE EMP_N = 2823 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4854'	WHERE EMP_N = 2824 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4880'	WHERE EMP_N = 2827 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4873'	WHERE EMP_N = 2828 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4887'	WHERE EMP_N = 2829 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '12345'	WHERE EMP_N = 2830 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4865'	WHERE EMP_N = 2835 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4863'	WHERE EMP_N = 2837 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4868'	WHERE EMP_N = 2839 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '6142018'	WHERE EMP_N = 2842 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4864'	WHERE EMP_N = 2844 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4910'	WHERE EMP_N = 2847 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4920'	WHERE EMP_N = 2851 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4835'	WHERE EMP_N = 2856 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4902'	WHERE EMP_N = 2876 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4862'	WHERE EMP_N = 2877 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4894'	WHERE EMP_N = 2880 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4618'	WHERE EMP_N = 2884 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4673'	WHERE EMP_N = 2887 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3760'	WHERE EMP_N = 2890 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4891'	WHERE EMP_N = 2893 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4516'	WHERE EMP_N = 2894 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4936'	WHERE EMP_N = 2908 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4889'	WHERE EMP_N = 2932 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4897'	WHERE EMP_N = 2933 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4851'	WHERE EMP_N = 2934 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4855'	WHERE EMP_N = 2938 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4892'	WHERE EMP_N = 2939 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4896'	WHERE EMP_N = 2940 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4991'	WHERE EMP_N = 2941 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3076'	WHERE EMP_N = 2947 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4008'	WHERE EMP_N = 2954 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3890'	WHERE EMP_N = 2956 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4893'	WHERE EMP_N = 2958 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4493'	WHERE EMP_N = 2960 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4517'	WHERE EMP_N = 2961 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4566'	WHERE EMP_N = 2962 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5814'	WHERE EMP_N = 2963 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4497'	WHERE EMP_N = 2964 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3856'	WHERE EMP_N = 2967 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3753'	WHERE EMP_N = 2969 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3700'	WHERE EMP_N = 2970 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3981'	WHERE EMP_N = 2972 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4519'	WHERE EMP_N = 2973 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4571'	WHERE EMP_N = 2975 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4606'	WHERE EMP_N = 2978 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3942'	WHERE EMP_N = 2981 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4401'	WHERE EMP_N = 2986 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4477'	WHERE EMP_N = 2987 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5124'	WHERE EMP_N = 2989 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4576'	WHERE EMP_N = 2991 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4444'	WHERE EMP_N = 2992 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4472'	WHERE EMP_N = 2995 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4727'	WHERE EMP_N = 2996 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3979'	WHERE EMP_N = 2997 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4513'	WHERE EMP_N = 2999 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3716'	WHERE EMP_N = 3000 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4504'	WHERE EMP_N = 3001 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4496'	WHERE EMP_N = 3002 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4628'	WHERE EMP_N = 3005 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4584'	WHERE EMP_N = 3006 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4440'	WHERE EMP_N = 3007 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3768'	WHERE EMP_N = 3008 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3111'	WHERE EMP_N = 3009 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3757'	WHERE EMP_N = 3010 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4102'	WHERE EMP_N = 3011 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4410'	WHERE EMP_N = 3016 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3758'	WHERE EMP_N = 3017 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4619'	WHERE EMP_N = 3020 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4520'	WHERE EMP_N = 3022 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3412'	WHERE EMP_N = 3023 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4514'	WHERE EMP_N = 3024 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3731'	WHERE EMP_N = 3028 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4734'	WHERE EMP_N = 3029 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3649'	WHERE EMP_N = 3031 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4406'	WHERE EMP_N = 3032 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4112'	WHERE EMP_N = 3034 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4494'	WHERE EMP_N = 3035 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '1537'	WHERE EMP_N = 3036 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3782'	WHERE EMP_N = 3040 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3972'	WHERE EMP_N = 3041 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3993'	WHERE EMP_N = 3042 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3085'	WHERE EMP_N = 3046 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4720'	WHERE EMP_N = 3049 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4886'	WHERE EMP_N = 3051 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3696'	WHERE EMP_N = 3052 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3961'	WHERE EMP_N = 3053 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4620'	WHERE EMP_N = 3054 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4449'	WHERE EMP_N = 3055 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4498'	WHERE EMP_N = 3056 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3752'	WHERE EMP_N = 3057 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4614'	WHERE EMP_N = 3058 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4531'	WHERE EMP_N = 3061 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3107'	WHERE EMP_N = 3064 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4003'	WHERE EMP_N = 3065 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4568'	WHERE EMP_N = 3066 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3903'	WHERE EMP_N = 3068 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3786'	WHERE EMP_N = 3069 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4471'	WHERE EMP_N = 3070 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4537'	WHERE EMP_N = 3071 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4575'	WHERE EMP_N = 3075 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4608'	WHERE EMP_N = 3077 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4405'	WHERE EMP_N = 3078 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3984'	WHERE EMP_N = 3079 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4574'	WHERE EMP_N = 3080 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3671'	WHERE EMP_N = 3081 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3704'	WHERE EMP_N = 3082 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4776'	WHERE EMP_N = 3083 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4581'	WHERE EMP_N = 3084 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4651'	WHERE EMP_N = 3086 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4610'	WHERE EMP_N = 3088 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4535'	WHERE EMP_N = 3090 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4470'	WHERE EMP_N = 3091 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '13463'	WHERE EMP_N = 3095 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4723'	WHERE EMP_N = 3096 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4509'	WHERE EMP_N = 3097 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4463'	WHERE EMP_N = 3098 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4569'	WHERE EMP_N = 3102 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3668'	WHERE EMP_N = 3104 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4570'	WHERE EMP_N = 3105 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3635'	WHERE EMP_N = 3107 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4526'	WHERE EMP_N = 3108 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3683'	WHERE EMP_N = 3109 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3724'	WHERE EMP_N = 3110 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4443'	WHERE EMP_N = 3112 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4489'	WHERE EMP_N = 3113 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4442'	WHERE EMP_N = 3114 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4511'	WHERE EMP_N = 3115 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3666'	WHERE EMP_N = 3116 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4624'	WHERE EMP_N = 3117 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3063'	WHERE EMP_N = 3118 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4432'	WHERE EMP_N = 3119 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4882'	WHERE EMP_N = 3120 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3803'	WHERE EMP_N = 3122 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4883'	WHERE EMP_N = 3124 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4623'	WHERE EMP_N = 3127 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4881'	WHERE EMP_N = 3128 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4885'	WHERE EMP_N = 3129 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3737'	WHERE EMP_N = 3130 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3157'	WHERE EMP_N = 3131 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3973'	WHERE EMP_N = 3132 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4577'	WHERE EMP_N = 3133 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3708'	WHERE EMP_N = 3134 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3783'	WHERE EMP_N = 3136 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4848'	WHERE EMP_N = 3141 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4890'	WHERE EMP_N = 3144 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4895'	WHERE EMP_N = 3149 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4499'	WHERE EMP_N = 3151 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4668'	WHERE EMP_N = 3166 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4917'	WHERE EMP_N = 3168 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4816'	WHERE EMP_N = 3169 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4901'	WHERE EMP_N = 3170 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4918'	WHERE EMP_N = 3173 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4940'	WHERE EMP_N = 3174 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4761'	WHERE EMP_N = 3175 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4817'	WHERE EMP_N = 3176 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4923'	WHERE EMP_N = 3184 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4945'	WHERE EMP_N = 3190 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4921'	WHERE EMP_N = 3197 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4927'	WHERE EMP_N = 3202 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3062'	WHERE EMP_N = 3207 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4785'	WHERE EMP_N = 3210 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4922'	WHERE EMP_N = 3211 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4875'	WHERE EMP_N = 3216 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4534'	WHERE EMP_N = 3217 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3324'	WHERE EMP_N = 3222 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4527'	WHERE EMP_N = 3231 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4736'	WHERE EMP_N = 3238 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4774'	WHERE EMP_N = 3239 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4905'	WHERE EMP_N = 3240 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4907'	WHERE EMP_N = 3241 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4928'	WHERE EMP_N = 3243 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4925'	WHERE EMP_N = 3248 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4788'	WHERE EMP_N = 3250 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4611'	WHERE EMP_N = 3251 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4670'	WHERE EMP_N = 3254 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4433'	WHERE EMP_N = 3255 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4867'	WHERE EMP_N = 3256 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4972'	WHERE EMP_N = 3259 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4613'	WHERE EMP_N = 3260 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3061'	WHERE EMP_N = 3261 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3687'	WHERE EMP_N = 3263 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4898'	WHERE EMP_N = 3264 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4874'	WHERE EMP_N = 3266 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '47310'	WHERE EMP_N = 3270 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4476'	WHERE EMP_N = 3271 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4522'	WHERE EMP_N = 3272 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4919'	WHERE EMP_N = 3274 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4768'	WHERE EMP_N = 3275 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4490'	WHERE EMP_N = 3277 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4575'	WHERE EMP_N = 3278 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3414'	WHERE EMP_N = 3279 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4700'	WHERE EMP_N = 3280 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '3801'	WHERE EMP_N = 3290 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4699'	WHERE EMP_N = 3293 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4926'	WHERE EMP_N = 3294 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4929'	WHERE EMP_N = 3295 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4932'	WHERE EMP_N = 3300 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4931'	WHERE EMP_N = 3301 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4943'	WHERE EMP_N = 3302 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5002'	WHERE EMP_N = 3304 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4978'	WHERE EMP_N = 3305 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4942'	WHERE EMP_N = 3306 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4946'	WHERE EMP_N = 3307 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4941'	WHERE EMP_N = 3310 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5004'	WHERE EMP_N = 3311 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = 'CT02'	WHERE EMP_N = 3312 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5005'	WHERE EMP_N = 3313 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = 'CT04'	WHERE EMP_N = 3314 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = 'CT05'	WHERE EMP_N = 3315 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5003'	WHERE EMP_N = 3316 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4988'	WHERE EMP_N = 3317 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4948'	WHERE EMP_N = 3319 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4949'	WHERE EMP_N = 3320 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4953'	WHERE EMP_N = 3324 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4951'	WHERE EMP_N = 3325 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4950'	WHERE EMP_N = 3326 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4952'	WHERE EMP_N = 3327 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '1000'	WHERE EMP_N = 3328 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4957'	WHERE EMP_N = 3329 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4959'	WHERE EMP_N = 3330 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4960'	WHERE EMP_N = 3331 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4958'	WHERE EMP_N = 3332 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4955'	WHERE EMP_N = 3333 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4956'	WHERE EMP_N = 3334 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4964'	WHERE EMP_N = 3335 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4965'	WHERE EMP_N = 3336 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4966'	WHERE EMP_N = 3337 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4968'	WHERE EMP_N = 3338 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4969'	WHERE EMP_N = 3339 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4970'	WHERE EMP_N = 3340 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4971'	WHERE EMP_N = 3341 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4962'	WHERE EMP_N = 3342 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4963'	WHERE EMP_N = 3343 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4961'	WHERE EMP_N = 3344 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5081'	WHERE EMP_N = 3346 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4974'	WHERE EMP_N = 3347 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4975'	WHERE EMP_N = 3350 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4979'	WHERE EMP_N = 3355 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4980'	WHERE EMP_N = 3357 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4982'	WHERE EMP_N = 3359 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4983'	WHERE EMP_N = 3360 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4976'	WHERE EMP_N = 3361 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4985'	WHERE EMP_N = 3362 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '6179'	WHERE EMP_N = 3364 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4986'	WHERE EMP_N = 3365 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4987'	WHERE EMP_N = 3366 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4995'	WHERE EMP_N = 3367 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4992'	WHERE EMP_N = 3369 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4989'	WHERE EMP_N = 3371 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5000'	WHERE EMP_N = 3372 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4990'	WHERE EMP_N = 3373 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4991'	WHERE EMP_N = 3374 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4993'	WHERE EMP_N = 3375 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4996'	WHERE EMP_N = 3378 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4997'	WHERE EMP_N = 3379 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '1430'	WHERE EMP_N = 3380 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4998'	WHERE EMP_N = 3381 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5001'	WHERE EMP_N = 3384 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4999'	WHERE EMP_N = 3385 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '4975'	WHERE EMP_N = 3386 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5009'	WHERE EMP_N = 3388 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5010'	WHERE EMP_N = 3389 ;";
echo "<br>";
echo $sql = "UPDATE tblemployeeinfo SET EMP_NUMBER = '5024'	WHERE EMP_N = 3390 ;";
echo "<br>";
